/****************************************************************************************************************
@Author         : Jagan Periyakaruppan
@Date Created   : 5/03/2018
@Description    : Static class used in the order trigger to control the order trigger flow
****************************************************************************************************************/
public class ClsOpportunityTriggerStaticClass {
    public static boolean isExecuting = false;
}