/****************************************************************************************************************
@Author         : Jagan Periyakaruppan
@Date Created   : 3/07/2018
@Description    : Static class used in the order trigger to control the order trigger flow
****************************************************************************************************************/
public class ClsOrderTriggerStaticClass {
    public static boolean isExecuting = false;
}