/****************************************************************************
*@Description   : Gets all product SKU that are eligible for return for a return order.
Function: 1. When a return order is created, it gets all products on parent order. 
2. Gets all return orders for that parent order.
3. Calculates available quantity for each of products on original order, base don all return orders for a parent order.
4. Wraps up uinformaiton in a custom class and sends it back to caller.
****************************************************************************/
public class ClsReturnCreditOrderWrapper {
	
}